comment:
  require_changes: true  # Only post a comment if coverage changes.

coverage:
  range: 95..100 # coverage lower than 50 is red, higher than 90 green, between color code

  status:
    project: # settings affecting project coverage
      default:
        target: 100%

    # do not run coverage on patch nor changes
    patch: false
