name: Go tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15, 1.16, 1.17]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Tests
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v3.0.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Unit tests
        if: runner.os != 'Linux'
        run: |
          go test -race ./...

      - name: Run Unit tests
        if: runner.os == 'Linux'
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Send to Codecov
        if: runner.os == 'Linux'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: golangci/golangci-lint-action@v3.1.0
